# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qErJkw-JOVmnrkGP2gf21Ja7xmkScpuG
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import openai

openai.api_key = st.secrets["OPENAI_API_KEY"]

st.set_page_config(page_title="GenAI Career Advisor", layout="centered")
st.title("🔮 AI Career Advisor")
st.markdown("_Get career guidance powered by GenAI!_")

user_input = st.text_area("✍️ Describe your background, interests, and goals:")

def build_prompt(user_text):
    return f"""
You are a career recommendation assistant.
Based on the user's background and interests, suggest:
1. 2-3 suitable career paths
2. In-demand tools/technologies for each
3. Top online resources or courses to start
4. Final tips or motivational line

User Profile:
{user_text}

Respond clearly with bullet points.
"""

if st.button("🎯 Get Recommendations") and user_input.strip():
    with st.spinner("Thinking..."):
        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a helpful career guide."},
                    {"role": "user", "content": build_prompt(user_input)}
                ],
                temperature=0.7,
                max_tokens=500
            )
            reply = response['choices'][0]['message']['content']
            st.success("Here’s your personalized advice:")
            st.markdown(reply)
        except Exception as e:
            st.error(f"Something went wrong: {e}")

st.markdown("---")
st.markdown("Created by Rima Hazra | Powered by OpenAI")